version: '3.8'

services:

  pg:
    image: postgres    
    ports: 
      - 5432:5432
    volumes: 
      - pg_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    user: postgres    

  pgadmin:
    image: dpage/pgadmin4    
    environment: 
      PGADMIN_DEFAULT_EMAIL: '1@1.ru'
      PGADMIN_DEFAULT_PASSWORD: 'pgadmin'
    ports: 
      - 5555:80


volumes: 
  pg_data:
